import { useEffect, useState } from "react";
import Header from "../../components/Header";
import Sidebar from "../../components/Sidebar";

const DISORDER_META = {
  ASD:     { label: "Autism Spectrum Disorder",    color: "#6366f1", bg: "rgba(99,102,241,0.15)" },
  SZ:      { label: "Schizophrenia",               color: "#f43f5e", bg: "rgba(244,63,94,0.15)"  },
  BD:      { label: "Bipolar Disorder",            color: "#f59e0b", bg: "rgba(245,158,11,0.15)" },
  SAD:     { label: "Seasonal Affective Disorder", color: "#06b6d4", bg: "rgba(6,182,212,0.15)" },
  DA:      { label: "Drug Addiction",              color: "#ec4899", bg: "rgba(236,72,153,0.15)" },
  Healthy: { label: "No diagnosed disorder",       color: "#22c55e", bg: "rgba(34,197,94,0.15)"  },
};

export default function PatientResults() {
  const patientId = localStorage.getItem("patientId");
  const patientName = localStorage.getItem("patientName");
  const [results, setResults] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`http://localhost:5001/api/results/patient/${patientId}`)
      .then(res => res.json())
      .then(data => {
        if (data.results && data.results.length > 0) {
          // Take the most recent prediction
          setResults(data.results[0]);
        } else {
          setResults(null);
        }
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [patientId]);

  return (
    <div className="min-h-screen bg-[#f3faf7] text-slate-800 font-sans">
      <Header />
      <div className="flex min-h-[calc(100vh-72px)]">
        <Sidebar className="w-64" />
        
        <div className="flex-1 p-10 max-w-5xl">
          <h1 className="text-3xl font-bold text-slate-800 mb-2">
            My Test Results
          </h1>
          <p className="text-slate-500 mb-8">
            These are the predictions algorithmically generated by your Doctor using the standard FL Network.
          </p>

          <div className="bg-white border border-slate-200 rounded-2xl p-8 shadow-sm">
            {loading ? (
              <p className="text-emerald-500 animate-pulse font-semibold">Fetching latest inferences...</p>
            ) : results ? (
              (() => {
                const meta = DISORDER_META[results.predictedDisorder] || DISORDER_META.Healthy;
                const sev = results.confidence || 0;
                return (
                  <div className="p-8 rounded-2xl border" style={{ borderColor: `${meta.color}50`, backgroundColor: `${meta.color}05` }}>
                    <div className="flex items-center gap-3 mb-6">
                      <span className="text-4xl text-slate-400">🩺</span>
                      <div>
                        <h3 className="text-xl font-bold text-slate-800">{patientName}</h3>
                        <p className="text-sm text-slate-500">Diagnosis Date: {new Date(results.createdAt).toLocaleDateString()}</p>
                      </div>
                    </div>

                    <div className="flex flex-col md:flex-row justify-between items-center gap-6 p-6 rounded-xl bg-slate-50 border border-slate-200">
                      <div>
                        <p className="text-sm uppercase tracking-widest font-bold text-slate-500 mb-1">Predicted Disorder</p>
                        <h2 className="text-4xl font-black" style={{ color: meta.color }}>
                          {meta.label}
                        </h2>
                      </div>

                      <div className="text-right md:min-w-[200px]">
                        <p className="text-sm uppercase tracking-widest font-bold text-slate-500 mb-1">Severity Match</p>
                        <div className="flex items-center justify-end gap-3">
                          <span className={`text-3xl font-black ${sev > 75 ? 'text-emerald-500' : sev > 50 ? 'text-amber-500' : 'text-rose-500'}`}>
                            {sev.toFixed(1)}%
                          </span>
                        </div>
                        <div className="w-full h-2 mt-2 bg-slate-200 rounded-full overflow-hidden">
                          <div className="h-full rounded-full" style={{ width: `${sev}%`, backgroundColor: meta.color }}></div>
                        </div>
                      </div>
                    </div>

                    <div className="mt-6 text-sm text-slate-600 p-4 border-l-4 border-slate-300 bg-slate-50">
                      <strong>Note:</strong> This assessment is generated via Neural Network algorithmic prediction. Please discuss this explicitly with your Doctor during your next appointment.
                    </div>
                  </div>
                );
              })()
            ) : (
              <div className="py-20 flex flex-col items-center justify-center text-center">
                <span className="text-6xl mb-4">⏳</span>
                <h3 className="text-xl font-bold text-slate-700">Results will be updated soon!</h3>
                <p className="text-slate-500 mt-2 max-w-md">
                  Your Doctor has not yet uploaded your specific dataset to the Federated Learning model. Please check back later.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
